# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: BDD Test Framework (Cucumber+Junit CI with Gradle)

on:
  push:
    branches: [ "settingsbattery", "main" ]

  #permissions:
  #contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code to GitHub Actions runner
        uses: actions/checkout@v3
      - name: Set up JDK 11 on the ubuntu runner
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: clean test --tests "nl.example.testrunners.SettingsTest"
